// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXxyXtQjhotylJCgXymPFB1OvU9rnYZb4',
    appId: '1:510014216261:web:a42b99cb4e001d1bdaab2c',
    messagingSenderId: '510014216261',
    projectId: 'dissipate',
    authDomain: 'dissipate.firebaseapp.com',
    storageBucket: 'dissipate.appspot.com',
    measurementId: 'G-9LQSXSHM3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-XyHi-7tSvXchXhAh7nZNmxL3vciNUWk',
    appId: '1:510014216261:android:ffd1a99f012c81a2daab2c',
    messagingSenderId: '510014216261',
    projectId: 'dissipate',
    storageBucket: 'dissipate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDImShFI3IoV8jlY32GeleZdD_TQwy16Kg',
    appId: '1:510014216261:ios:9f34772955b7b0e7daab2c',
    messagingSenderId: '510014216261',
    projectId: 'dissipate',
    storageBucket: 'dissipate.appspot.com',
    iosClientId: '510014216261-r268rhbuurcb67qmg2c0tefokp5iimjb.apps.googleusercontent.com',
    iosBundleId: 'io.186282.dissipate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDImShFI3IoV8jlY32GeleZdD_TQwy16Kg',
    appId: '1:510014216261:ios:9f34772955b7b0e7daab2c',
    messagingSenderId: '510014216261',
    projectId: 'dissipate',
    storageBucket: 'dissipate.appspot.com',
    iosClientId: '510014216261-r268rhbuurcb67qmg2c0tefokp5iimjb.apps.googleusercontent.com',
    iosBundleId: 'io.186282.dissipate',
  );
}
